fix the python output in floating section in "Python Fortran Rosetta Stone" page
fortran-lang/webpage pull request #458
Opened 2024-09-08 12:29 UTC by Zhou-Jiangcheng

Fixed the Python output in the "Floating Point Numbers" section in the explanatory notes.

2024-09-08 12:31 UTC, Zhou-Jiangcheng commented
![图片](https://github.com/user-attachments/assets/79a9423f-de6f-4fb1-bbfe-ad2101984d61)
The result in Python cell, in line 4
f = float(1 / 2) # 0.0
seems wrong in Python 3.11, numpy 1.26.4. It should be 0.5.
And I also tried float32(1/2), it returns the same result.

2024-09-09 22:18 UTC, zmoon commented
> f = float(1 / 2) # 0.0
> seems wrong in Python 3.11, numpy 1.26.4. It should be 0.5.

Yes, it was correct in Python 2, but for Python 3 the behavior of `/` for two `int`s changed.

2026-07-31 08:50 UTC, joewallwork requested changes
Perhaps worth mentioning that this is in Python 3 in the text then?

2026-08-22 06:41 UTC, closed without merging

2026-08-22 06:41 UTC, Zhou-Jiangcheng commented
It is not a bug, sorry. In Python2, it is right!

2026-08-25 06:14 UTC, joewallwork commented
> It is not a bug, sorry. In Python2, it is right!

Sure, but Python 3 is now the standard. I would still be in support of this change if you want to reopen it and make the requested change.